#!/bin/bash

M=$(./get_arithm_mean $@)
k=0
for i in $@  
do
	var_arr[k]=$(echo ${i}  ${M} | awk '{print ( ( $1 - $2 ) * ( $1 - $2 ) )}')
	let k++
done

varianz=$(./get_arithm_mean ${var_arr[*]})

t=$(echo ${varianz} | awk '{printf "%d", $1}')
[ ${t} -lt 1 ] && echo 0.0 || \
echo ${varianz} | awk '{printf "%.2f ", sqrt($1)}'
