#!/bin/bash

PATTERN=$1
POSITION=$2

j=0
i=0
for t in $@
do
	if [ $j -le 1 ]
	then 
		let j++
	else 
		files[$i]=$t
		let i++
	fi
done

j=0
for i in ${files[*]} 
do
	cat $i | grep $PATTERN |\
	while read line 
	do
		entity[$j]=$(echo $POSITION $line | awk '{pos=$1 ; print $(pos+1)}' | tr ',' ' ' | tr '\%' ' ')
		printf "%s " ${entity[$j]}
		let j++
	done
done 
printf "\n"
