#!/bin/sh

DRIVER=if_ringmap
SCRIPTS_DIR="../scripts/"
DRIVER_SRC_DIR="../em/"

echo

kldstat | grep ${DRIVER} > /dev/null 
if [ $? -eq 0 ]
then 
	echo "Unload "${DRIVER}" module"
	kldunload ${DRIVER}.ko
	sleep 1
fi
echo
echo "Build and load ringmap driver"
${SCRIPTS_DIR}/ringmap_build && kldload ${DRIVER_SRC_DIR}/${DRIVER}.ko
